Train route
eriansha/Jaketi pull request #6
Opened 2023-07-21 14:47 UTC by mymycucu

Add 
- banner
- temp bound picker
- rounded corner and view extention for banner
Update
- theme: add color
- modeldata: transform estimate destination
- trainstation: update model for estimateDestination
- schedule list & row: route mapping, and estimate dest
- LiveSceduleView: update ui banner and list
- viewmodel: add transform estimateDestination and destination time

2023-07-21 18:08 UTC, eriansha requested changes
nitip ya :p @mymycucu

2023-07-21 18:08 UTC, eriansha commented on Jaketi/Features/Presenters/Extensions/RoundedCorner.swift
> +//
ini bukan di extensions. taro di `component` aja

2023-07-21 18:08 UTC, eriansha commented on Jaketi/Core/Constants/Theme.swift
> +        static let primary = Color(red: 0.173, green: 0.271, blue: 0.502)
ga pake hex aja?

2023-07-21 18:08 UTC, eriansha commented on Jaketi/Features/Models/TrainStation.swift
> +}
ini ga jadi dipake kan? hapus aja

2023-07-21 18:08 UTC, eriansha commented on Jaketi/Features/Presenters/Components/ScheduleRow.swift
>                              Text(isArrived ? "Tiba di Peron" : "\(estimateTimeInMinute) menit")
`Tibe di Peron` sama tulisan `menit` nya dipindahin ke `Constant/Prompt` aja

nanti jadi tinggal manggil constantnya aja, minimizing kesalahan penulisan

2023-07-21 18:08 UTC, eriansha commented on Jaketi/Features/Presenters/Components/TrainBanner.swift
> +    private let isArrived: Bool
di `TrainBanner` cuma perlu **satu schedule** sama tujuannya. j

adi kayaknya cukup dgn passing satu entity dari `DepartureSchedule`.

2023-07-21 18:08 UTC, eriansha commented on Jaketi/Features/Presenters/Views/ContentView.swift
> +                .navigationTitle("Schedule")
`Schedule` pindahin ke `Prompt` tapi yang di extensions `Title`

2023-07-21 18:08 UTC, eriansha commented on Jaketi/Features/ViewModels/TrainStationViewModel.swift
> +                    currentEstimateDestinations[indexEstimate].stationName = "Transform Error"
sebenarnya bukan error tapi maksudnya kalo ga ada datanya. better dibikin `-` aja.

2023-07-22 01:57 UTC, mymycucu commented on Jaketi/Core/Constants/Theme.swift
> +        static let primary = Color(red: 0.173, green: 0.271, blue: 0.502)
kalo mau pake hex harus bikin extention color dulu

2023-07-23 06:14 UTC, eriansha approved these changes

2023-07-23 06:14 UTC, merged